// ExplainDrawer — modal overlay for AI-generated explanations.
// Phase ε ships the shell. Phase γ wires it to /api/v1/ai/explain.

import { useEffect } from 'react';

export default function ExplainDrawer({ open, onClose, context }) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, background: 'rgba(15,23,42,0.45)',
        display: 'flex', justifyContent: 'flex-end', zIndex: 1000,
      }}
    >
      <div
        role="dialog" aria-modal="true" aria-label="AI Explanation"
        onClick={(e) => e.stopPropagation()}
        style={{
          width: 'min(520px, 100vw)', height: '100vh', background: '#fff',
          boxShadow: '-12px 0 32px rgba(0,0,0,0.18)',
          display: 'flex', flexDirection: 'column',
        }}
      >
        <header style={{
          padding: '16px 20px', borderBottom: '1px solid #e2e8f0',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        }}>
          <h3 style={{ margin: 0, fontSize: 16 }}>🤖 AI Explanation</h3>
          <button
            onClick={onClose}
            aria-label="Close"
            style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: '#64748b' }}
          >×</button>
        </header>
        <section style={{ padding: '20px', overflow: 'auto', flex: 1 }}>
          {context && (
            <div style={{
              padding: 12, background: '#f8fafc', borderRadius: 6, marginBottom: 16,
              fontSize: 12, color: '#475569',
            }}>
              <div style={{ fontWeight: 600, marginBottom: 4 }}>Context passed</div>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, monospace' }}>
                {JSON.stringify(context, null, 2)}
              </pre>
            </div>
          )}
          <div style={{
            padding: 24, background: 'rgba(59,130,246,0.05)',
            border: '1px dashed #3b82f6', borderRadius: 8,
            textAlign: 'center',
          }}>
            <div style={{ fontSize: 40, marginBottom: 12 }}>🚧</div>
            <h4 style={{ margin: '0 0 8px', fontSize: 15 }}>AI explanation engine ships in Phase γ</h4>
            <p style={{ margin: 0, fontSize: 13, color: '#475569', lineHeight: 1.5 }}>
              When Phase γ lands, this panel will show a grounded markdown narrative
              generated by Ollama + hybrid RAG over the sales-context corpus, with
              citations for every claim.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
